'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("DotsGame.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _10easy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("10easy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _10easyDown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("10easyDown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _10hard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("10hard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _10hardDown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("10hardDown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _10medium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("10medium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _10mediumDown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("10mediumDown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _15easy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("15easy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _15easyDown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("15easyDown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _15hard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("15hard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _15hardDown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("15hardDown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _15medium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("15medium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _15mediumDown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("15mediumDown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _20easy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("20easy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _20easyDown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("20easyDown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _20hard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("20hard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _20hardDown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("20hardDown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _20medium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("20medium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _20mediumDown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("20mediumDown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _25easy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("25easy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _25easyDown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("25easyDown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _25hard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("25hard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _25hardDown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("25hardDown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _25medium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("25medium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _25mediumDown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("25mediumDown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _5easy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("5easy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _5easyDown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("5easyDown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _5hard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("5hard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _5hardDown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("5hardDown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _5medium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("5medium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _5mediumDown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("5mediumDown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property btnBack() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnBack", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property btnBackOver() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnBackOver", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property btnEasy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnEasy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property btnHard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnHard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property btnHardDisabled() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnHardDisabled", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property btnInstructions() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnInstructions", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property btnMainMenu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnMainMenu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property btnMainMenu1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnMainMenu1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property btnMedium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnMedium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property btnMediumDisabled() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnMediumDisabled", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property btnPlay() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnPlay", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property btnPlayOver() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnPlayOver", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property frmGameEndBackground() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("frmGameEndBackground", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property frmLockedPlayerInfoBackground() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("frmLockedPlayerInfoBackground", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property frmLockedPlayerInfoBackground1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("frmLockedPlayerInfoBackground1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property frmPlayerInfoBackground() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("frmPlayerInfoBackground", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property frmPlayersEasyBackground() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("frmPlayersEasyBackground", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property frmPlayersEasyBackground1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("frmPlayersEasyBackground1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property frmPlayersHardBackground() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("frmPlayersHardBackground", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property frmPlayersHardBackground1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("frmPlayersHardBackground1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property frmPlayersMediumBackground() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("frmPlayersMediumBackground", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property frmPlayersMediumBackground1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("frmPlayersMediumBackground1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property frmStartBackground() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("frmStartBackground", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property invincible() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("invincible", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property picDanger() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picDanger", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property picGet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picGet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property picPauseDown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picPauseDown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property picPauseUp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picPauseUp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property picPlayDown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picPlayDown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property picPlayerHue10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picPlayerHue10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property picPlayerHue100() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picPlayerHue100", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property picPlayerHue110() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picPlayerHue110", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property picPlayerHue120() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picPlayerHue120", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property picPlayerHue130() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picPlayerHue130", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property picPlayerHue140() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picPlayerHue140", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property picPlayerHue150() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picPlayerHue150", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property picPlayerHue160() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picPlayerHue160", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property picPlayerHue170() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picPlayerHue170", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property picPlayerHue180() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picPlayerHue180", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property picPlayerHue190() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picPlayerHue190", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property picPlayerHue20() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picPlayerHue20", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property picPlayerHue200() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picPlayerHue200", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property picPlayerHue210() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picPlayerHue210", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property picPlayerHue220() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picPlayerHue220", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property picPlayerHue230() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picPlayerHue230", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property picPlayerHue240() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picPlayerHue240", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property picPlayerHue250() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picPlayerHue250", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property picPlayerHue260() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picPlayerHue260", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property picPlayerHue270() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picPlayerHue270", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property picPlayerHue280() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picPlayerHue280", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property picPlayerHue290() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picPlayerHue290", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property picPlayerHue30() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picPlayerHue30", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property picPlayerHue300() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picPlayerHue300", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property picPlayerHue310() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picPlayerHue310", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property picPlayerHue320() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picPlayerHue320", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property picPlayerHue330() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picPlayerHue330", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property picPlayerHue340() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picPlayerHue340", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property picPlayerHue350() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picPlayerHue350", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property picPlayerHue360() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picPlayerHue360", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property picPlayerHue40() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picPlayerHue40", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property picPlayerHue50() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picPlayerHue50", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property picPlayerHue60() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picPlayerHue60", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property picPlayerHue70() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picPlayerHue70", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property picPlayerHue80() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picPlayerHue80", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property picPlayerHue90() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picPlayerHue90", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property picPlayerSQ() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picPlayerSQ", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property picPlayUp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picPlayUp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property player1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("player1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property player10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("player10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property player11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("player11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property player12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("player12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property player13() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("player13", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property player14() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("player14", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property player15() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("player15", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property player16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("player16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property player17() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("player17", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property player18() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("player18", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property player2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("player2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property player3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("player3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property player4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("player4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property player5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("player5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property player6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("player6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property player7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("player7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property player8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("player8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property player9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("player9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property players1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("players1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property players10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("players10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property players10over() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("players10over", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property players11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("players11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property players11over() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("players11over", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property players12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("players12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property players12over() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("players12over", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property players13() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("players13", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property players13over() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("players13over", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property players14() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("players14", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property players14over() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("players14over", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property players15() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("players15", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property players15over() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("players15over", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property players16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("players16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property players16over() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("players16over", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property players17() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("players17", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property players17over() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("players17over", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property players18() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("players18", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property players18over() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("players18over", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property players1over() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("players1over", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property players2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("players2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property players2over() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("players2over", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property players3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("players3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property players3over() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("players3over", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property players4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("players4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property players4over() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("players4over", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property players5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("players5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property players5over() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("players5over", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property players6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("players6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property players6over() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("players6over", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property players7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("players7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property players7over() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("players7over", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property players8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("players8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property players8over() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("players8over", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property players9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("players9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property players9over() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("players9over", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property songBackgroundMusic() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("songBackgroundMusic", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property thud() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("thud", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
