'Josh Gibbs
'Period 2
'June 5 2011
'Blocks (Final Project)
'frmCharacterslist v6.5.1944 r7

'To-Do

Public Class frmSelectedCharacterInfo

    'Closes the window and it's transparancy layer on click
    Private Sub btnBack_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnBack.Click
        Me.Hide()
        frmTransparantLayer.Hide()
    End Sub

    'animates the back button on mouse hover
    Private Sub btnBack_MouseHover(ByVal sender As Object, ByVal e As System.EventArgs) Handles btnBack.MouseHover
        btnBack.Image = My.Resources.btnBackOver
    End Sub

    'animates the back button on mouse leave
    Private Sub btnBack_MouseLeave(ByVal sender As Object, ByVal e As System.EventArgs) Handles btnBack.MouseLeave
        btnBack.Image = My.Resources.btnBack
    End Sub


    Private Sub picPlay_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles picPlay.Click

        'Gets the center of the usable bounds on frmGameplay
        Dim centerx As Int16 = (frmGameplay.varRightBounds - frmGameplay.varLeftBounds) / 2 - frmCharactersList.varSelectedSize / 2 + frmGameplay.varLeftBounds
        Dim centery As Int16 = (frmGameplay.varBottomBounds - frmGameplay.varTopBounds) / 2 - frmCharactersList.varSelectedSize / 2 + frmGameplay.varTopBounds

        'sets the high score
        If frmGameplay.varGameDifficulty = "Easy" Then
            frmGameplay.lblHighScore.Text = frmStartMenu.varGameEasyHighScore
            'PIC = EASY
        ElseIf frmGameplay.varGameDifficulty = "Medium" Then
            frmGameplay.lblHighScore.Text = frmStartMenu.varGameMediumHighScore
            'PIC = MEDIUM
        ElseIf frmGameplay.varGameDifficulty = "Hard" Then
            frmGameplay.lblHighScore.Text = frmStartMenu.varGameHardHighscore
            'PIC = HARD
        End If

        'sets player propertis
        frmGameplay.picPlayer.SetBounds(centerx, centery, frmCharactersList.varSelectedSize, frmCharactersList.varSelectedSize)
        frmGameplay.picPlayer.Image = frmCharactersList.player(frmCharactersList.varSelectedCharacter - 1)
        frmGameplay.varPlayerSpeed = frmCharactersList.varSelectedSpeed
        frmGameplay.pgbInvincible.Maximum = frmCharactersList.varSelectedInvincibility
        frmGameplay.pgbInvincible.Value = frmCharactersList.varSelectedInvincibility

        'enables timers
        frmGameplay.tmrBlueBlockMovement.Enabled = True
        frmGameplay.tmrIntersectChecks.Enabled = True
        frmGameplay.tmrPlayerMovement.Enabled = True

        'sets up invincibility array
        setInvincibilityArray()

        'switches forms
        frmGameplay.Show()
        frmGameplay.Location = frmCharactersList.Location
        frmCharactersList.Hide()
        frmTransparantLayer.Hide()
        Me.Hide()

    End Sub

    'animates the play button on mouse hover
    Private Sub picPlay_MouseHover(ByVal sender As Object, ByVal e As System.EventArgs) Handles picPlay.MouseHover
        'picPlay.Image = My.Resources.btnPlayOver
    End Sub

    'animates the play button on mouse leave
    Private Sub picPlay_MouseLeave(ByVal sender As Object, ByVal e As System.EventArgs) Handles picPlay.MouseLeave
        picPlay.Image = My.Resources.btnPlay
    End Sub

    'sets the invincibility array on frmGameplay from selected character
    Public Sub setInvincibilityArray()
        If frmCharactersList.varSelectedCharacter = 1 Then
            frmGameplay.aryCharacterInvincibilityImages(0) = My.Resources.Player1Hue10
            frmGameplay.aryCharacterInvincibilityImages(1) = My.Resources.Player1Hue20
            frmGameplay.aryCharacterInvincibilityImages(2) = My.Resources.Player1Hue30
            frmGameplay.aryCharacterInvincibilityImages(3) = My.Resources.Player1Hue40
            frmGameplay.aryCharacterInvincibilityImages(4) = My.Resources.Player1Hue50
            frmGameplay.aryCharacterInvincibilityImages(5) = My.Resources.Player1Hue60
            frmGameplay.aryCharacterInvincibilityImages(6) = My.Resources.Player1Hue70
            frmGameplay.aryCharacterInvincibilityImages(7) = My.Resources.Player1Hue80
            frmGameplay.aryCharacterInvincibilityImages(8) = My.Resources.Player1Hue90
            frmGameplay.aryCharacterInvincibilityImages(9) = My.Resources.Player1Hue100
            frmGameplay.aryCharacterInvincibilityImages(10) = My.Resources.Player1Hue110
            frmGameplay.aryCharacterInvincibilityImages(11) = My.Resources.Player1Hue120
            frmGameplay.aryCharacterInvincibilityImages(12) = My.Resources.Player1Hue130
            frmGameplay.aryCharacterInvincibilityImages(13) = My.Resources.Player1Hue140
            frmGameplay.aryCharacterInvincibilityImages(14) = My.Resources.Player1Hue150
            frmGameplay.aryCharacterInvincibilityImages(15) = My.Resources.Player1Hue160
            frmGameplay.aryCharacterInvincibilityImages(16) = My.Resources.Player1Hue170
            frmGameplay.aryCharacterInvincibilityImages(17) = My.Resources.Player1Hue180
            frmGameplay.aryCharacterInvincibilityImages(18) = My.Resources.Player1Hue190
            frmGameplay.aryCharacterInvincibilityImages(19) = My.Resources.Player1Hue200
            frmGameplay.aryCharacterInvincibilityImages(20) = My.Resources.Player1Hue210
            frmGameplay.aryCharacterInvincibilityImages(21) = My.Resources.Player1Hue220
            frmGameplay.aryCharacterInvincibilityImages(22) = My.Resources.Player1Hue230
            frmGameplay.aryCharacterInvincibilityImages(23) = My.Resources.Player1Hue240
            frmGameplay.aryCharacterInvincibilityImages(24) = My.Resources.Player1Hue250
            frmGameplay.aryCharacterInvincibilityImages(25) = My.Resources.Player1Hue260
            frmGameplay.aryCharacterInvincibilityImages(26) = My.Resources.Player1Hue270
            frmGameplay.aryCharacterInvincibilityImages(27) = My.Resources.Player1Hue280
            frmGameplay.aryCharacterInvincibilityImages(28) = My.Resources.Player1Hue290
            frmGameplay.aryCharacterInvincibilityImages(29) = My.Resources.Player1Hue300
            frmGameplay.aryCharacterInvincibilityImages(30) = My.Resources.Player1Hue310
            frmGameplay.aryCharacterInvincibilityImages(31) = My.Resources.Player1Hue320
            frmGameplay.aryCharacterInvincibilityImages(32) = My.Resources.Player1Hue330
            frmGameplay.aryCharacterInvincibilityImages(33) = My.Resources.Player1Hue340
            frmGameplay.aryCharacterInvincibilityImages(34) = My.Resources.Player1Hue350
            frmGameplay.aryCharacterInvincibilityImages(35) = My.Resources.Player1Hue360
        ElseIf frmCharactersList.varSelectedCharacter = 2 Then
            frmGameplay.aryCharacterInvincibilityImages(0) = My.Resources.Player2Hue10
            frmGameplay.aryCharacterInvincibilityImages(1) = My.Resources.Player2Hue20
            frmGameplay.aryCharacterInvincibilityImages(2) = My.Resources.Player2Hue30
            frmGameplay.aryCharacterInvincibilityImages(3) = My.Resources.Player2Hue40
            frmGameplay.aryCharacterInvincibilityImages(4) = My.Resources.Player2Hue50
            frmGameplay.aryCharacterInvincibilityImages(5) = My.Resources.Player2Hue60
            frmGameplay.aryCharacterInvincibilityImages(6) = My.Resources.Player2Hue70
            frmGameplay.aryCharacterInvincibilityImages(7) = My.Resources.Player2Hue80
            frmGameplay.aryCharacterInvincibilityImages(8) = My.Resources.Player2Hue90
            frmGameplay.aryCharacterInvincibilityImages(9) = My.Resources.Player2Hue100
            frmGameplay.aryCharacterInvincibilityImages(10) = My.Resources.Player2Hue110
            frmGameplay.aryCharacterInvincibilityImages(11) = My.Resources.Player2Hue120
            frmGameplay.aryCharacterInvincibilityImages(12) = My.Resources.Player2Hue130
            frmGameplay.aryCharacterInvincibilityImages(13) = My.Resources.Player2Hue140
            frmGameplay.aryCharacterInvincibilityImages(14) = My.Resources.Player2Hue150
            frmGameplay.aryCharacterInvincibilityImages(15) = My.Resources.Player2Hue160
            frmGameplay.aryCharacterInvincibilityImages(16) = My.Resources.Player2Hue170
            frmGameplay.aryCharacterInvincibilityImages(17) = My.Resources.Player2Hue180
            frmGameplay.aryCharacterInvincibilityImages(18) = My.Resources.Player2Hue190
            frmGameplay.aryCharacterInvincibilityImages(19) = My.Resources.Player2Hue200
            frmGameplay.aryCharacterInvincibilityImages(20) = My.Resources.Player2Hue210
            frmGameplay.aryCharacterInvincibilityImages(21) = My.Resources.Player2Hue220
            frmGameplay.aryCharacterInvincibilityImages(22) = My.Resources.Player2Hue230
            frmGameplay.aryCharacterInvincibilityImages(23) = My.Resources.Player2Hue240
            frmGameplay.aryCharacterInvincibilityImages(24) = My.Resources.Player2Hue250
            frmGameplay.aryCharacterInvincibilityImages(25) = My.Resources.Player2Hue260
            frmGameplay.aryCharacterInvincibilityImages(26) = My.Resources.Player2Hue270
            frmGameplay.aryCharacterInvincibilityImages(27) = My.Resources.Player2Hue280
            frmGameplay.aryCharacterInvincibilityImages(28) = My.Resources.Player2Hue290
            frmGameplay.aryCharacterInvincibilityImages(29) = My.Resources.Player2Hue300
            frmGameplay.aryCharacterInvincibilityImages(30) = My.Resources.Player2Hue310
            frmGameplay.aryCharacterInvincibilityImages(31) = My.Resources.Player2Hue320
            frmGameplay.aryCharacterInvincibilityImages(32) = My.Resources.Player2Hue330
            frmGameplay.aryCharacterInvincibilityImages(33) = My.Resources.Player2Hue340
            frmGameplay.aryCharacterInvincibilityImages(34) = My.Resources.Player2Hue350
            frmGameplay.aryCharacterInvincibilityImages(35) = My.Resources.Player2Hue360
        ElseIf frmCharactersList.varSelectedCharacter = 3 Then
            frmGameplay.aryCharacterInvincibilityImages(0) = My.Resources.Player3Hue10
            frmGameplay.aryCharacterInvincibilityImages(1) = My.Resources.Player3Hue20
            frmGameplay.aryCharacterInvincibilityImages(2) = My.Resources.Player3Hue30
            frmGameplay.aryCharacterInvincibilityImages(3) = My.Resources.Player3Hue40
            frmGameplay.aryCharacterInvincibilityImages(4) = My.Resources.Player3Hue50
            frmGameplay.aryCharacterInvincibilityImages(5) = My.Resources.Player3Hue60
            frmGameplay.aryCharacterInvincibilityImages(6) = My.Resources.Player3Hue70
            frmGameplay.aryCharacterInvincibilityImages(7) = My.Resources.Player3Hue80
            frmGameplay.aryCharacterInvincibilityImages(8) = My.Resources.Player3Hue90
            frmGameplay.aryCharacterInvincibilityImages(9) = My.Resources.Player3Hue100
            frmGameplay.aryCharacterInvincibilityImages(10) = My.Resources.Player3Hue110
            frmGameplay.aryCharacterInvincibilityImages(11) = My.Resources.Player3Hue120
            frmGameplay.aryCharacterInvincibilityImages(12) = My.Resources.Player3Hue130
            frmGameplay.aryCharacterInvincibilityImages(13) = My.Resources.Player3Hue140
            frmGameplay.aryCharacterInvincibilityImages(14) = My.Resources.Player3Hue150
            frmGameplay.aryCharacterInvincibilityImages(15) = My.Resources.Player3Hue160
            frmGameplay.aryCharacterInvincibilityImages(16) = My.Resources.Player3Hue170
            frmGameplay.aryCharacterInvincibilityImages(17) = My.Resources.Player3Hue180
            frmGameplay.aryCharacterInvincibilityImages(18) = My.Resources.Player3Hue190
            frmGameplay.aryCharacterInvincibilityImages(19) = My.Resources.Player3Hue200
            frmGameplay.aryCharacterInvincibilityImages(20) = My.Resources.Player3Hue210
            frmGameplay.aryCharacterInvincibilityImages(21) = My.Resources.Player3Hue220
            frmGameplay.aryCharacterInvincibilityImages(22) = My.Resources.Player3Hue230
            frmGameplay.aryCharacterInvincibilityImages(23) = My.Resources.Player3Hue240
            frmGameplay.aryCharacterInvincibilityImages(24) = My.Resources.Player3Hue250
            frmGameplay.aryCharacterInvincibilityImages(25) = My.Resources.Player3Hue260
            frmGameplay.aryCharacterInvincibilityImages(26) = My.Resources.Player3Hue270
            frmGameplay.aryCharacterInvincibilityImages(27) = My.Resources.Player3Hue280
            frmGameplay.aryCharacterInvincibilityImages(28) = My.Resources.Player3Hue290
            frmGameplay.aryCharacterInvincibilityImages(29) = My.Resources.Player3Hue300
            frmGameplay.aryCharacterInvincibilityImages(30) = My.Resources.Player3Hue310
            frmGameplay.aryCharacterInvincibilityImages(31) = My.Resources.Player3Hue320
            frmGameplay.aryCharacterInvincibilityImages(32) = My.Resources.Player3Hue330
            frmGameplay.aryCharacterInvincibilityImages(33) = My.Resources.Player3Hue340
            frmGameplay.aryCharacterInvincibilityImages(34) = My.Resources.Player3Hue350
            frmGameplay.aryCharacterInvincibilityImages(35) = My.Resources.Player3Hue360
        ElseIf frmCharactersList.varSelectedCharacter = 4 Then
            frmGameplay.aryCharacterInvincibilityImages(0) = My.Resources.Player4Hue10
            frmGameplay.aryCharacterInvincibilityImages(1) = My.Resources.Player4Hue20
            frmGameplay.aryCharacterInvincibilityImages(2) = My.Resources.Player4Hue30
            frmGameplay.aryCharacterInvincibilityImages(3) = My.Resources.Player4Hue40
            frmGameplay.aryCharacterInvincibilityImages(4) = My.Resources.Player4Hue50
            frmGameplay.aryCharacterInvincibilityImages(5) = My.Resources.Player4Hue60
            frmGameplay.aryCharacterInvincibilityImages(6) = My.Resources.Player4Hue70
            frmGameplay.aryCharacterInvincibilityImages(7) = My.Resources.Player4Hue80
            frmGameplay.aryCharacterInvincibilityImages(8) = My.Resources.Player4Hue90
            frmGameplay.aryCharacterInvincibilityImages(9) = My.Resources.Player4Hue100
            frmGameplay.aryCharacterInvincibilityImages(10) = My.Resources.Player4Hue110
            frmGameplay.aryCharacterInvincibilityImages(11) = My.Resources.Player4Hue120
            frmGameplay.aryCharacterInvincibilityImages(12) = My.Resources.Player4Hue130
            frmGameplay.aryCharacterInvincibilityImages(13) = My.Resources.Player4Hue140
            frmGameplay.aryCharacterInvincibilityImages(14) = My.Resources.Player4Hue150
            frmGameplay.aryCharacterInvincibilityImages(15) = My.Resources.Player4Hue160
            frmGameplay.aryCharacterInvincibilityImages(16) = My.Resources.Player4Hue170
            frmGameplay.aryCharacterInvincibilityImages(17) = My.Resources.Player4Hue180
            frmGameplay.aryCharacterInvincibilityImages(18) = My.Resources.Player4Hue190
            frmGameplay.aryCharacterInvincibilityImages(19) = My.Resources.Player4Hue200
            frmGameplay.aryCharacterInvincibilityImages(20) = My.Resources.Player4Hue210
            frmGameplay.aryCharacterInvincibilityImages(21) = My.Resources.Player4Hue220
            frmGameplay.aryCharacterInvincibilityImages(22) = My.Resources.Player4Hue230
            frmGameplay.aryCharacterInvincibilityImages(23) = My.Resources.Player4Hue240
            frmGameplay.aryCharacterInvincibilityImages(24) = My.Resources.Player4Hue250
            frmGameplay.aryCharacterInvincibilityImages(25) = My.Resources.Player4Hue260
            frmGameplay.aryCharacterInvincibilityImages(26) = My.Resources.Player4Hue270
            frmGameplay.aryCharacterInvincibilityImages(27) = My.Resources.Player4Hue280
            frmGameplay.aryCharacterInvincibilityImages(28) = My.Resources.Player4Hue290
            frmGameplay.aryCharacterInvincibilityImages(29) = My.Resources.Player4Hue300
            frmGameplay.aryCharacterInvincibilityImages(30) = My.Resources.Player4Hue310
            frmGameplay.aryCharacterInvincibilityImages(31) = My.Resources.Player4Hue320
            frmGameplay.aryCharacterInvincibilityImages(32) = My.Resources.Player4Hue330
            frmGameplay.aryCharacterInvincibilityImages(33) = My.Resources.Player4Hue340
            frmGameplay.aryCharacterInvincibilityImages(34) = My.Resources.Player4Hue350
            frmGameplay.aryCharacterInvincibilityImages(35) = My.Resources.Player4Hue360
        ElseIf frmCharactersList.varSelectedCharacter = 5 Then
            frmGameplay.aryCharacterInvincibilityImages(0) = My.Resources.Player5Hue10
            frmGameplay.aryCharacterInvincibilityImages(1) = My.Resources.Player5Hue20
            frmGameplay.aryCharacterInvincibilityImages(2) = My.Resources.Player5Hue30
            frmGameplay.aryCharacterInvincibilityImages(3) = My.Resources.Player5Hue40
            frmGameplay.aryCharacterInvincibilityImages(4) = My.Resources.Player5Hue50
            frmGameplay.aryCharacterInvincibilityImages(5) = My.Resources.Player5Hue60
            frmGameplay.aryCharacterInvincibilityImages(6) = My.Resources.Player5Hue70
            frmGameplay.aryCharacterInvincibilityImages(7) = My.Resources.Player5Hue80
            frmGameplay.aryCharacterInvincibilityImages(8) = My.Resources.Player5Hue90
            frmGameplay.aryCharacterInvincibilityImages(9) = My.Resources.Player5Hue100
            frmGameplay.aryCharacterInvincibilityImages(10) = My.Resources.Player5Hue110
            frmGameplay.aryCharacterInvincibilityImages(11) = My.Resources.Player5Hue120
            frmGameplay.aryCharacterInvincibilityImages(12) = My.Resources.Player5Hue130
            frmGameplay.aryCharacterInvincibilityImages(13) = My.Resources.Player5Hue140
            frmGameplay.aryCharacterInvincibilityImages(14) = My.Resources.Player5Hue150
            frmGameplay.aryCharacterInvincibilityImages(15) = My.Resources.Player5Hue160
            frmGameplay.aryCharacterInvincibilityImages(16) = My.Resources.Player5Hue170
            frmGameplay.aryCharacterInvincibilityImages(17) = My.Resources.Player5Hue180
            frmGameplay.aryCharacterInvincibilityImages(18) = My.Resources.Player5Hue190
            frmGameplay.aryCharacterInvincibilityImages(19) = My.Resources.Player5Hue200
            frmGameplay.aryCharacterInvincibilityImages(20) = My.Resources.Player5Hue210
            frmGameplay.aryCharacterInvincibilityImages(21) = My.Resources.Player5Hue220
            frmGameplay.aryCharacterInvincibilityImages(22) = My.Resources.Player5Hue230
            frmGameplay.aryCharacterInvincibilityImages(23) = My.Resources.Player5Hue240
            frmGameplay.aryCharacterInvincibilityImages(24) = My.Resources.Player5Hue250
            frmGameplay.aryCharacterInvincibilityImages(25) = My.Resources.Player5Hue260
            frmGameplay.aryCharacterInvincibilityImages(26) = My.Resources.Player5Hue270
            frmGameplay.aryCharacterInvincibilityImages(27) = My.Resources.Player5Hue280
            frmGameplay.aryCharacterInvincibilityImages(28) = My.Resources.Player5Hue290
            frmGameplay.aryCharacterInvincibilityImages(29) = My.Resources.Player5Hue300
            frmGameplay.aryCharacterInvincibilityImages(30) = My.Resources.Player5Hue310
            frmGameplay.aryCharacterInvincibilityImages(31) = My.Resources.Player5Hue320
            frmGameplay.aryCharacterInvincibilityImages(32) = My.Resources.Player5Hue330
            frmGameplay.aryCharacterInvincibilityImages(33) = My.Resources.Player5Hue340
            frmGameplay.aryCharacterInvincibilityImages(34) = My.Resources.Player5Hue350
            frmGameplay.aryCharacterInvincibilityImages(35) = My.Resources.Player5Hue360
        ElseIf frmCharactersList.varSelectedCharacter = 6 Then
            frmGameplay.aryCharacterInvincibilityImages(0) = My.Resources.Player6Hue10
            frmGameplay.aryCharacterInvincibilityImages(1) = My.Resources.Player6Hue20
            frmGameplay.aryCharacterInvincibilityImages(2) = My.Resources.Player6Hue30
            frmGameplay.aryCharacterInvincibilityImages(3) = My.Resources.Player6Hue40
            frmGameplay.aryCharacterInvincibilityImages(4) = My.Resources.Player6Hue50
            frmGameplay.aryCharacterInvincibilityImages(5) = My.Resources.Player6Hue60
            frmGameplay.aryCharacterInvincibilityImages(6) = My.Resources.Player6Hue70
            frmGameplay.aryCharacterInvincibilityImages(7) = My.Resources.Player6Hue80
            frmGameplay.aryCharacterInvincibilityImages(8) = My.Resources.Player6Hue90
            frmGameplay.aryCharacterInvincibilityImages(9) = My.Resources.Player6Hue100
            frmGameplay.aryCharacterInvincibilityImages(10) = My.Resources.Player6Hue110
            frmGameplay.aryCharacterInvincibilityImages(11) = My.Resources.Player6Hue120
            frmGameplay.aryCharacterInvincibilityImages(12) = My.Resources.Player6Hue130
            frmGameplay.aryCharacterInvincibilityImages(13) = My.Resources.Player6Hue140
            frmGameplay.aryCharacterInvincibilityImages(14) = My.Resources.Player6Hue150
            frmGameplay.aryCharacterInvincibilityImages(15) = My.Resources.Player6Hue160
            frmGameplay.aryCharacterInvincibilityImages(16) = My.Resources.Player6Hue170
            frmGameplay.aryCharacterInvincibilityImages(17) = My.Resources.Player6Hue180
            frmGameplay.aryCharacterInvincibilityImages(18) = My.Resources.Player6Hue190
            frmGameplay.aryCharacterInvincibilityImages(19) = My.Resources.Player6Hue200
            frmGameplay.aryCharacterInvincibilityImages(20) = My.Resources.Player6Hue210
            frmGameplay.aryCharacterInvincibilityImages(21) = My.Resources.Player6Hue220
            frmGameplay.aryCharacterInvincibilityImages(22) = My.Resources.Player6Hue230
            frmGameplay.aryCharacterInvincibilityImages(23) = My.Resources.Player6Hue240
            frmGameplay.aryCharacterInvincibilityImages(24) = My.Resources.Player6Hue250
            frmGameplay.aryCharacterInvincibilityImages(25) = My.Resources.Player6Hue260
            frmGameplay.aryCharacterInvincibilityImages(26) = My.Resources.Player6Hue270
            frmGameplay.aryCharacterInvincibilityImages(27) = My.Resources.Player6Hue280
            frmGameplay.aryCharacterInvincibilityImages(28) = My.Resources.Player6Hue290
            frmGameplay.aryCharacterInvincibilityImages(29) = My.Resources.Player6Hue300
            frmGameplay.aryCharacterInvincibilityImages(30) = My.Resources.Player6Hue310
            frmGameplay.aryCharacterInvincibilityImages(31) = My.Resources.Player6Hue320
            frmGameplay.aryCharacterInvincibilityImages(32) = My.Resources.Player6Hue330
            frmGameplay.aryCharacterInvincibilityImages(33) = My.Resources.Player6Hue340
            frmGameplay.aryCharacterInvincibilityImages(34) = My.Resources.Player6Hue350
            frmGameplay.aryCharacterInvincibilityImages(35) = My.Resources.Player6Hue360
        ElseIf frmCharactersList.varSelectedCharacter = 7 Then
            frmGameplay.aryCharacterInvincibilityImages(0) = My.Resources.Player7Hue10
            frmGameplay.aryCharacterInvincibilityImages(1) = My.Resources.Player7Hue20
            frmGameplay.aryCharacterInvincibilityImages(2) = My.Resources.Player7Hue30
            frmGameplay.aryCharacterInvincibilityImages(3) = My.Resources.Player7Hue40
            frmGameplay.aryCharacterInvincibilityImages(4) = My.Resources.Player7Hue50
            frmGameplay.aryCharacterInvincibilityImages(5) = My.Resources.Player7Hue60
            frmGameplay.aryCharacterInvincibilityImages(6) = My.Resources.Player7Hue70
            frmGameplay.aryCharacterInvincibilityImages(7) = My.Resources.Player7Hue80
            frmGameplay.aryCharacterInvincibilityImages(8) = My.Resources.Player7Hue90
            frmGameplay.aryCharacterInvincibilityImages(9) = My.Resources.Player7Hue100
            frmGameplay.aryCharacterInvincibilityImages(10) = My.Resources.Player7Hue110
            frmGameplay.aryCharacterInvincibilityImages(11) = My.Resources.Player7Hue120
            frmGameplay.aryCharacterInvincibilityImages(12) = My.Resources.Player7Hue130
            frmGameplay.aryCharacterInvincibilityImages(13) = My.Resources.Player7Hue140
            frmGameplay.aryCharacterInvincibilityImages(14) = My.Resources.Player7Hue150
            frmGameplay.aryCharacterInvincibilityImages(15) = My.Resources.Player7Hue160
            frmGameplay.aryCharacterInvincibilityImages(16) = My.Resources.Player7Hue170
            frmGameplay.aryCharacterInvincibilityImages(17) = My.Resources.Player7Hue180
            frmGameplay.aryCharacterInvincibilityImages(18) = My.Resources.Player7Hue190
            frmGameplay.aryCharacterInvincibilityImages(19) = My.Resources.Player7Hue200
            frmGameplay.aryCharacterInvincibilityImages(20) = My.Resources.Player7Hue210
            frmGameplay.aryCharacterInvincibilityImages(21) = My.Resources.Player7Hue220
            frmGameplay.aryCharacterInvincibilityImages(22) = My.Resources.Player7Hue230
            frmGameplay.aryCharacterInvincibilityImages(23) = My.Resources.Player7Hue240
            frmGameplay.aryCharacterInvincibilityImages(24) = My.Resources.Player7Hue250
            frmGameplay.aryCharacterInvincibilityImages(25) = My.Resources.Player7Hue260
            frmGameplay.aryCharacterInvincibilityImages(26) = My.Resources.Player7Hue270
            frmGameplay.aryCharacterInvincibilityImages(27) = My.Resources.Player7Hue280
            frmGameplay.aryCharacterInvincibilityImages(28) = My.Resources.Player7Hue290
            frmGameplay.aryCharacterInvincibilityImages(29) = My.Resources.Player7Hue300
            frmGameplay.aryCharacterInvincibilityImages(30) = My.Resources.Player7Hue310
            frmGameplay.aryCharacterInvincibilityImages(31) = My.Resources.Player7Hue320
            frmGameplay.aryCharacterInvincibilityImages(32) = My.Resources.Player7Hue330
            frmGameplay.aryCharacterInvincibilityImages(33) = My.Resources.Player7Hue340
            frmGameplay.aryCharacterInvincibilityImages(34) = My.Resources.Player7Hue350
            frmGameplay.aryCharacterInvincibilityImages(35) = My.Resources.Player7Hue360
        ElseIf frmCharactersList.varSelectedCharacter = 8 Then
            frmGameplay.aryCharacterInvincibilityImages(0) = My.Resources.Player8Hue10
            frmGameplay.aryCharacterInvincibilityImages(1) = My.Resources.Player8Hue20
            frmGameplay.aryCharacterInvincibilityImages(2) = My.Resources.Player8Hue30
            frmGameplay.aryCharacterInvincibilityImages(3) = My.Resources.Player8Hue40
            frmGameplay.aryCharacterInvincibilityImages(4) = My.Resources.Player8Hue50
            frmGameplay.aryCharacterInvincibilityImages(5) = My.Resources.Player8Hue60
            frmGameplay.aryCharacterInvincibilityImages(6) = My.Resources.Player8Hue70
            frmGameplay.aryCharacterInvincibilityImages(7) = My.Resources.Player8Hue80
            frmGameplay.aryCharacterInvincibilityImages(8) = My.Resources.Player8Hue90
            frmGameplay.aryCharacterInvincibilityImages(9) = My.Resources.Player8Hue100
            frmGameplay.aryCharacterInvincibilityImages(10) = My.Resources.Player8Hue110
            frmGameplay.aryCharacterInvincibilityImages(11) = My.Resources.Player8Hue120
            frmGameplay.aryCharacterInvincibilityImages(12) = My.Resources.Player8Hue130
            frmGameplay.aryCharacterInvincibilityImages(13) = My.Resources.Player8Hue140
            frmGameplay.aryCharacterInvincibilityImages(14) = My.Resources.Player8Hue150
            frmGameplay.aryCharacterInvincibilityImages(15) = My.Resources.Player8Hue160
            frmGameplay.aryCharacterInvincibilityImages(16) = My.Resources.Player8Hue170
            frmGameplay.aryCharacterInvincibilityImages(17) = My.Resources.Player8Hue180
            frmGameplay.aryCharacterInvincibilityImages(18) = My.Resources.Player8Hue190
            frmGameplay.aryCharacterInvincibilityImages(19) = My.Resources.Player8Hue200
            frmGameplay.aryCharacterInvincibilityImages(20) = My.Resources.Player8Hue210
            frmGameplay.aryCharacterInvincibilityImages(21) = My.Resources.Player8Hue220
            frmGameplay.aryCharacterInvincibilityImages(22) = My.Resources.Player8Hue230
            frmGameplay.aryCharacterInvincibilityImages(23) = My.Resources.Player8Hue240
            frmGameplay.aryCharacterInvincibilityImages(24) = My.Resources.Player8Hue250
            frmGameplay.aryCharacterInvincibilityImages(25) = My.Resources.Player8Hue260
            frmGameplay.aryCharacterInvincibilityImages(26) = My.Resources.Player8Hue270
            frmGameplay.aryCharacterInvincibilityImages(27) = My.Resources.Player8Hue280
            frmGameplay.aryCharacterInvincibilityImages(28) = My.Resources.Player8Hue290
            frmGameplay.aryCharacterInvincibilityImages(29) = My.Resources.Player8Hue300
            frmGameplay.aryCharacterInvincibilityImages(30) = My.Resources.Player8Hue310
            frmGameplay.aryCharacterInvincibilityImages(31) = My.Resources.Player8Hue320
            frmGameplay.aryCharacterInvincibilityImages(32) = My.Resources.Player8Hue330
            frmGameplay.aryCharacterInvincibilityImages(33) = My.Resources.Player8Hue340
            frmGameplay.aryCharacterInvincibilityImages(34) = My.Resources.Player8Hue350
            frmGameplay.aryCharacterInvincibilityImages(35) = My.Resources.Player8Hue360
        ElseIf frmCharactersList.varSelectedCharacter = 9 Then
            frmGameplay.aryCharacterInvincibilityImages(0) = My.Resources.Player9Hue10
            frmGameplay.aryCharacterInvincibilityImages(1) = My.Resources.Player9Hue20
            frmGameplay.aryCharacterInvincibilityImages(2) = My.Resources.Player9Hue30
            frmGameplay.aryCharacterInvincibilityImages(3) = My.Resources.Player9Hue40
            frmGameplay.aryCharacterInvincibilityImages(4) = My.Resources.Player9Hue50
            frmGameplay.aryCharacterInvincibilityImages(5) = My.Resources.Player9Hue60
            frmGameplay.aryCharacterInvincibilityImages(6) = My.Resources.Player9Hue70
            frmGameplay.aryCharacterInvincibilityImages(7) = My.Resources.Player9Hue80
            frmGameplay.aryCharacterInvincibilityImages(8) = My.Resources.Player9Hue90
            frmGameplay.aryCharacterInvincibilityImages(9) = My.Resources.Player9Hue100
            frmGameplay.aryCharacterInvincibilityImages(10) = My.Resources.Player9Hue110
            frmGameplay.aryCharacterInvincibilityImages(11) = My.Resources.Player9Hue120
            frmGameplay.aryCharacterInvincibilityImages(12) = My.Resources.Player9Hue130
            frmGameplay.aryCharacterInvincibilityImages(13) = My.Resources.Player9Hue140
            frmGameplay.aryCharacterInvincibilityImages(14) = My.Resources.Player9Hue150
            frmGameplay.aryCharacterInvincibilityImages(15) = My.Resources.Player9Hue160
            frmGameplay.aryCharacterInvincibilityImages(16) = My.Resources.Player9Hue170
            frmGameplay.aryCharacterInvincibilityImages(17) = My.Resources.Player9Hue180
            frmGameplay.aryCharacterInvincibilityImages(18) = My.Resources.Player9Hue190
            frmGameplay.aryCharacterInvincibilityImages(19) = My.Resources.Player9Hue200
            frmGameplay.aryCharacterInvincibilityImages(20) = My.Resources.Player9Hue210
            frmGameplay.aryCharacterInvincibilityImages(21) = My.Resources.Player9Hue220
            frmGameplay.aryCharacterInvincibilityImages(22) = My.Resources.Player9Hue230
            frmGameplay.aryCharacterInvincibilityImages(23) = My.Resources.Player9Hue240
            frmGameplay.aryCharacterInvincibilityImages(24) = My.Resources.Player9Hue250
            frmGameplay.aryCharacterInvincibilityImages(25) = My.Resources.Player9Hue260
            frmGameplay.aryCharacterInvincibilityImages(26) = My.Resources.Player9Hue270
            frmGameplay.aryCharacterInvincibilityImages(27) = My.Resources.Player9Hue280
            frmGameplay.aryCharacterInvincibilityImages(28) = My.Resources.Player9Hue290
            frmGameplay.aryCharacterInvincibilityImages(29) = My.Resources.Player9Hue300
            frmGameplay.aryCharacterInvincibilityImages(30) = My.Resources.Player9Hue310
            frmGameplay.aryCharacterInvincibilityImages(31) = My.Resources.Player9Hue320
            frmGameplay.aryCharacterInvincibilityImages(32) = My.Resources.Player9Hue330
            frmGameplay.aryCharacterInvincibilityImages(33) = My.Resources.Player9Hue340
            frmGameplay.aryCharacterInvincibilityImages(34) = My.Resources.Player9Hue350
            frmGameplay.aryCharacterInvincibilityImages(35) = My.Resources.Player9Hue360
        ElseIf frmCharactersList.varSelectedCharacter = 10 Then
            frmGameplay.aryCharacterInvincibilityImages(0) = My.Resources.Player10Hue10
            frmGameplay.aryCharacterInvincibilityImages(1) = My.Resources.Player10Hue20
            frmGameplay.aryCharacterInvincibilityImages(2) = My.Resources.Player10Hue30
            frmGameplay.aryCharacterInvincibilityImages(3) = My.Resources.Player10Hue40
            frmGameplay.aryCharacterInvincibilityImages(4) = My.Resources.Player10Hue50
            frmGameplay.aryCharacterInvincibilityImages(5) = My.Resources.Player10Hue60
            frmGameplay.aryCharacterInvincibilityImages(6) = My.Resources.Player10Hue70
            frmGameplay.aryCharacterInvincibilityImages(7) = My.Resources.Player10Hue80
            frmGameplay.aryCharacterInvincibilityImages(8) = My.Resources.Player10Hue90
            frmGameplay.aryCharacterInvincibilityImages(9) = My.Resources.Player10Hue100
            frmGameplay.aryCharacterInvincibilityImages(10) = My.Resources.Player10Hue110
            frmGameplay.aryCharacterInvincibilityImages(11) = My.Resources.Player10Hue120
            frmGameplay.aryCharacterInvincibilityImages(12) = My.Resources.Player10Hue130
            frmGameplay.aryCharacterInvincibilityImages(13) = My.Resources.Player10Hue140
            frmGameplay.aryCharacterInvincibilityImages(14) = My.Resources.Player10Hue150
            frmGameplay.aryCharacterInvincibilityImages(15) = My.Resources.Player10Hue160
            frmGameplay.aryCharacterInvincibilityImages(16) = My.Resources.Player10Hue170
            frmGameplay.aryCharacterInvincibilityImages(17) = My.Resources.Player10Hue180
            frmGameplay.aryCharacterInvincibilityImages(18) = My.Resources.Player10Hue190
            frmGameplay.aryCharacterInvincibilityImages(19) = My.Resources.Player10Hue200
            frmGameplay.aryCharacterInvincibilityImages(20) = My.Resources.Player10Hue210
            frmGameplay.aryCharacterInvincibilityImages(21) = My.Resources.Player10Hue220
            frmGameplay.aryCharacterInvincibilityImages(22) = My.Resources.Player10Hue230
            frmGameplay.aryCharacterInvincibilityImages(23) = My.Resources.Player10Hue240
            frmGameplay.aryCharacterInvincibilityImages(24) = My.Resources.Player10Hue250
            frmGameplay.aryCharacterInvincibilityImages(25) = My.Resources.Player10Hue260
            frmGameplay.aryCharacterInvincibilityImages(26) = My.Resources.Player10Hue270
            frmGameplay.aryCharacterInvincibilityImages(27) = My.Resources.Player10Hue280
            frmGameplay.aryCharacterInvincibilityImages(28) = My.Resources.Player10Hue290
            frmGameplay.aryCharacterInvincibilityImages(29) = My.Resources.Player10Hue300
            frmGameplay.aryCharacterInvincibilityImages(30) = My.Resources.Player10Hue310
            frmGameplay.aryCharacterInvincibilityImages(31) = My.Resources.Player10Hue320
            frmGameplay.aryCharacterInvincibilityImages(32) = My.Resources.Player10Hue330
            frmGameplay.aryCharacterInvincibilityImages(33) = My.Resources.Player10Hue340
            frmGameplay.aryCharacterInvincibilityImages(34) = My.Resources.Player10Hue350
            frmGameplay.aryCharacterInvincibilityImages(35) = My.Resources.Player10Hue360
        ElseIf frmCharactersList.varSelectedCharacter = 11 Then
            frmGameplay.aryCharacterInvincibilityImages(0) = My.Resources.Player11Hue10
            frmGameplay.aryCharacterInvincibilityImages(1) = My.Resources.Player11Hue20
            frmGameplay.aryCharacterInvincibilityImages(2) = My.Resources.Player11Hue30
            frmGameplay.aryCharacterInvincibilityImages(3) = My.Resources.Player11Hue40
            frmGameplay.aryCharacterInvincibilityImages(4) = My.Resources.Player11Hue50
            frmGameplay.aryCharacterInvincibilityImages(5) = My.Resources.Player11Hue60
            frmGameplay.aryCharacterInvincibilityImages(6) = My.Resources.Player11Hue70
            frmGameplay.aryCharacterInvincibilityImages(7) = My.Resources.Player11Hue80
            frmGameplay.aryCharacterInvincibilityImages(8) = My.Resources.Player11Hue90
            frmGameplay.aryCharacterInvincibilityImages(9) = My.Resources.Player11Hue100
            frmGameplay.aryCharacterInvincibilityImages(10) = My.Resources.Player11Hue110
            frmGameplay.aryCharacterInvincibilityImages(11) = My.Resources.Player11Hue120
            frmGameplay.aryCharacterInvincibilityImages(12) = My.Resources.Player11Hue130
            frmGameplay.aryCharacterInvincibilityImages(13) = My.Resources.Player11Hue140
            frmGameplay.aryCharacterInvincibilityImages(14) = My.Resources.Player11Hue150
            frmGameplay.aryCharacterInvincibilityImages(15) = My.Resources.Player11Hue160
            frmGameplay.aryCharacterInvincibilityImages(16) = My.Resources.Player11Hue170
            frmGameplay.aryCharacterInvincibilityImages(17) = My.Resources.Player11Hue180
            frmGameplay.aryCharacterInvincibilityImages(18) = My.Resources.Player11Hue190
            frmGameplay.aryCharacterInvincibilityImages(19) = My.Resources.Player11Hue200
            frmGameplay.aryCharacterInvincibilityImages(20) = My.Resources.Player11Hue210
            frmGameplay.aryCharacterInvincibilityImages(21) = My.Resources.Player11Hue220
            frmGameplay.aryCharacterInvincibilityImages(22) = My.Resources.Player11Hue230
            frmGameplay.aryCharacterInvincibilityImages(23) = My.Resources.Player11Hue240
            frmGameplay.aryCharacterInvincibilityImages(24) = My.Resources.Player11Hue250
            frmGameplay.aryCharacterInvincibilityImages(25) = My.Resources.Player11Hue260
            frmGameplay.aryCharacterInvincibilityImages(26) = My.Resources.Player11Hue270
            frmGameplay.aryCharacterInvincibilityImages(27) = My.Resources.Player11Hue280
            frmGameplay.aryCharacterInvincibilityImages(28) = My.Resources.Player11Hue290
            frmGameplay.aryCharacterInvincibilityImages(29) = My.Resources.Player11Hue300
            frmGameplay.aryCharacterInvincibilityImages(30) = My.Resources.Player11Hue310
            frmGameplay.aryCharacterInvincibilityImages(31) = My.Resources.Player11Hue320
            frmGameplay.aryCharacterInvincibilityImages(32) = My.Resources.Player11Hue330
            frmGameplay.aryCharacterInvincibilityImages(33) = My.Resources.Player11Hue340
            frmGameplay.aryCharacterInvincibilityImages(34) = My.Resources.Player11Hue350
            frmGameplay.aryCharacterInvincibilityImages(35) = My.Resources.Player11Hue360
        ElseIf frmCharactersList.varSelectedCharacter = 12 Then
            frmGameplay.aryCharacterInvincibilityImages(0) = My.Resources.Player12Hue10
            frmGameplay.aryCharacterInvincibilityImages(1) = My.Resources.Player12Hue20
            frmGameplay.aryCharacterInvincibilityImages(2) = My.Resources.Player12Hue30
            frmGameplay.aryCharacterInvincibilityImages(3) = My.Resources.Player12Hue40
            frmGameplay.aryCharacterInvincibilityImages(4) = My.Resources.Player12Hue50
            frmGameplay.aryCharacterInvincibilityImages(5) = My.Resources.Player12Hue60
            frmGameplay.aryCharacterInvincibilityImages(6) = My.Resources.Player12Hue70
            frmGameplay.aryCharacterInvincibilityImages(7) = My.Resources.Player12Hue80
            frmGameplay.aryCharacterInvincibilityImages(8) = My.Resources.Player12Hue90
            frmGameplay.aryCharacterInvincibilityImages(9) = My.Resources.Player12Hue100
            frmGameplay.aryCharacterInvincibilityImages(10) = My.Resources.Player12Hue110
            frmGameplay.aryCharacterInvincibilityImages(11) = My.Resources.Player12Hue120
            frmGameplay.aryCharacterInvincibilityImages(12) = My.Resources.Player12Hue130
            frmGameplay.aryCharacterInvincibilityImages(13) = My.Resources.Player12Hue140
            frmGameplay.aryCharacterInvincibilityImages(14) = My.Resources.Player12Hue150
            frmGameplay.aryCharacterInvincibilityImages(15) = My.Resources.Player12Hue160
            frmGameplay.aryCharacterInvincibilityImages(16) = My.Resources.Player12Hue170
            frmGameplay.aryCharacterInvincibilityImages(17) = My.Resources.Player12Hue180
            frmGameplay.aryCharacterInvincibilityImages(18) = My.Resources.Player12Hue190
            frmGameplay.aryCharacterInvincibilityImages(19) = My.Resources.Player12Hue200
            frmGameplay.aryCharacterInvincibilityImages(20) = My.Resources.Player12Hue210
            frmGameplay.aryCharacterInvincibilityImages(21) = My.Resources.Player12Hue220
            frmGameplay.aryCharacterInvincibilityImages(22) = My.Resources.Player12Hue230
            frmGameplay.aryCharacterInvincibilityImages(23) = My.Resources.Player12Hue240
            frmGameplay.aryCharacterInvincibilityImages(24) = My.Resources.Player12Hue250
            frmGameplay.aryCharacterInvincibilityImages(25) = My.Resources.Player12Hue260
            frmGameplay.aryCharacterInvincibilityImages(26) = My.Resources.Player12Hue270
            frmGameplay.aryCharacterInvincibilityImages(27) = My.Resources.Player12Hue280
            frmGameplay.aryCharacterInvincibilityImages(28) = My.Resources.Player12Hue290
            frmGameplay.aryCharacterInvincibilityImages(29) = My.Resources.Player12Hue300
            frmGameplay.aryCharacterInvincibilityImages(30) = My.Resources.Player12Hue310
            frmGameplay.aryCharacterInvincibilityImages(31) = My.Resources.Player12Hue320
            frmGameplay.aryCharacterInvincibilityImages(32) = My.Resources.Player12Hue330
            frmGameplay.aryCharacterInvincibilityImages(33) = My.Resources.Player12Hue340
            frmGameplay.aryCharacterInvincibilityImages(34) = My.Resources.Player12Hue350
            frmGameplay.aryCharacterInvincibilityImages(35) = My.Resources.Player12Hue360
        ElseIf frmCharactersList.varSelectedCharacter = 13 Then
            frmGameplay.aryCharacterInvincibilityImages(0) = My.Resources.Player13Hue10
            frmGameplay.aryCharacterInvincibilityImages(1) = My.Resources.Player13Hue20
            frmGameplay.aryCharacterInvincibilityImages(2) = My.Resources.Player13Hue30
            frmGameplay.aryCharacterInvincibilityImages(3) = My.Resources.Player13Hue40
            frmGameplay.aryCharacterInvincibilityImages(4) = My.Resources.Player13Hue50
            frmGameplay.aryCharacterInvincibilityImages(5) = My.Resources.Player13Hue60
            frmGameplay.aryCharacterInvincibilityImages(6) = My.Resources.Player13Hue70
            frmGameplay.aryCharacterInvincibilityImages(7) = My.Resources.Player13Hue80
            frmGameplay.aryCharacterInvincibilityImages(8) = My.Resources.Player13Hue90
            frmGameplay.aryCharacterInvincibilityImages(9) = My.Resources.Player13Hue100
            frmGameplay.aryCharacterInvincibilityImages(10) = My.Resources.Player13Hue110
            frmGameplay.aryCharacterInvincibilityImages(11) = My.Resources.Player13Hue120
            frmGameplay.aryCharacterInvincibilityImages(12) = My.Resources.Player13Hue130
            frmGameplay.aryCharacterInvincibilityImages(13) = My.Resources.Player13Hue140
            frmGameplay.aryCharacterInvincibilityImages(14) = My.Resources.Player13Hue150
            frmGameplay.aryCharacterInvincibilityImages(15) = My.Resources.Player13Hue160
            frmGameplay.aryCharacterInvincibilityImages(16) = My.Resources.Player13Hue170
            frmGameplay.aryCharacterInvincibilityImages(17) = My.Resources.Player13Hue180
            frmGameplay.aryCharacterInvincibilityImages(18) = My.Resources.Player13Hue190
            frmGameplay.aryCharacterInvincibilityImages(19) = My.Resources.Player13Hue200
            frmGameplay.aryCharacterInvincibilityImages(20) = My.Resources.Player13Hue210
            frmGameplay.aryCharacterInvincibilityImages(21) = My.Resources.Player13Hue220
            frmGameplay.aryCharacterInvincibilityImages(22) = My.Resources.Player13Hue230
            frmGameplay.aryCharacterInvincibilityImages(23) = My.Resources.Player13Hue240
            frmGameplay.aryCharacterInvincibilityImages(24) = My.Resources.Player13Hue250
            frmGameplay.aryCharacterInvincibilityImages(25) = My.Resources.Player13Hue260
            frmGameplay.aryCharacterInvincibilityImages(26) = My.Resources.Player13Hue270
            frmGameplay.aryCharacterInvincibilityImages(27) = My.Resources.Player13Hue280
            frmGameplay.aryCharacterInvincibilityImages(28) = My.Resources.Player13Hue290
            frmGameplay.aryCharacterInvincibilityImages(29) = My.Resources.Player13Hue300
            frmGameplay.aryCharacterInvincibilityImages(30) = My.Resources.Player13Hue310
            frmGameplay.aryCharacterInvincibilityImages(31) = My.Resources.Player13Hue320
            frmGameplay.aryCharacterInvincibilityImages(32) = My.Resources.Player13Hue330
            frmGameplay.aryCharacterInvincibilityImages(33) = My.Resources.Player13Hue340
            frmGameplay.aryCharacterInvincibilityImages(34) = My.Resources.Player13Hue350
            frmGameplay.aryCharacterInvincibilityImages(35) = My.Resources.Player13Hue360
        ElseIf frmCharactersList.varSelectedCharacter = 14 Then
            frmGameplay.aryCharacterInvincibilityImages(0) = My.Resources.Player14Hue10
            frmGameplay.aryCharacterInvincibilityImages(1) = My.Resources.Player14Hue20
            frmGameplay.aryCharacterInvincibilityImages(2) = My.Resources.Player14Hue30
            frmGameplay.aryCharacterInvincibilityImages(3) = My.Resources.Player14Hue40
            frmGameplay.aryCharacterInvincibilityImages(4) = My.Resources.Player14Hue50
            frmGameplay.aryCharacterInvincibilityImages(5) = My.Resources.Player14Hue60
            frmGameplay.aryCharacterInvincibilityImages(6) = My.Resources.Player14Hue70
            frmGameplay.aryCharacterInvincibilityImages(7) = My.Resources.Player14Hue80
            frmGameplay.aryCharacterInvincibilityImages(8) = My.Resources.Player14Hue90
            frmGameplay.aryCharacterInvincibilityImages(9) = My.Resources.Player14Hue100
            frmGameplay.aryCharacterInvincibilityImages(10) = My.Resources.Player14Hue110
            frmGameplay.aryCharacterInvincibilityImages(11) = My.Resources.Player14Hue120
            frmGameplay.aryCharacterInvincibilityImages(12) = My.Resources.Player14Hue130
            frmGameplay.aryCharacterInvincibilityImages(13) = My.Resources.Player14Hue140
            frmGameplay.aryCharacterInvincibilityImages(14) = My.Resources.Player14Hue150
            frmGameplay.aryCharacterInvincibilityImages(15) = My.Resources.Player14Hue160
            frmGameplay.aryCharacterInvincibilityImages(16) = My.Resources.Player14Hue170
            frmGameplay.aryCharacterInvincibilityImages(17) = My.Resources.Player14Hue180
            frmGameplay.aryCharacterInvincibilityImages(18) = My.Resources.Player14Hue190
            frmGameplay.aryCharacterInvincibilityImages(19) = My.Resources.Player14Hue200
            frmGameplay.aryCharacterInvincibilityImages(20) = My.Resources.Player14Hue210
            frmGameplay.aryCharacterInvincibilityImages(21) = My.Resources.Player14Hue220
            frmGameplay.aryCharacterInvincibilityImages(22) = My.Resources.Player14Hue230
            frmGameplay.aryCharacterInvincibilityImages(23) = My.Resources.Player14Hue240
            frmGameplay.aryCharacterInvincibilityImages(24) = My.Resources.Player14Hue250
            frmGameplay.aryCharacterInvincibilityImages(25) = My.Resources.Player14Hue260
            frmGameplay.aryCharacterInvincibilityImages(26) = My.Resources.Player14Hue270
            frmGameplay.aryCharacterInvincibilityImages(27) = My.Resources.Player14Hue280
            frmGameplay.aryCharacterInvincibilityImages(28) = My.Resources.Player14Hue290
            frmGameplay.aryCharacterInvincibilityImages(29) = My.Resources.Player14Hue300
            frmGameplay.aryCharacterInvincibilityImages(30) = My.Resources.Player14Hue310
            frmGameplay.aryCharacterInvincibilityImages(31) = My.Resources.Player14Hue320
            frmGameplay.aryCharacterInvincibilityImages(32) = My.Resources.Player14Hue330
            frmGameplay.aryCharacterInvincibilityImages(33) = My.Resources.Player14Hue340
            frmGameplay.aryCharacterInvincibilityImages(34) = My.Resources.Player14Hue350
            frmGameplay.aryCharacterInvincibilityImages(35) = My.Resources.Player14Hue360
        ElseIf frmCharactersList.varSelectedCharacter = 15 Then
            frmGameplay.aryCharacterInvincibilityImages(0) = My.Resources.Player15Hue10
            frmGameplay.aryCharacterInvincibilityImages(1) = My.Resources.Player15Hue20
            frmGameplay.aryCharacterInvincibilityImages(2) = My.Resources.Player15Hue30
            frmGameplay.aryCharacterInvincibilityImages(3) = My.Resources.Player15Hue40
            frmGameplay.aryCharacterInvincibilityImages(4) = My.Resources.Player15Hue50
            frmGameplay.aryCharacterInvincibilityImages(5) = My.Resources.Player15Hue60
            frmGameplay.aryCharacterInvincibilityImages(6) = My.Resources.Player15Hue70
            frmGameplay.aryCharacterInvincibilityImages(7) = My.Resources.Player15Hue80
            frmGameplay.aryCharacterInvincibilityImages(8) = My.Resources.Player15Hue90
            frmGameplay.aryCharacterInvincibilityImages(9) = My.Resources.Player15Hue100
            frmGameplay.aryCharacterInvincibilityImages(10) = My.Resources.Player15Hue110
            frmGameplay.aryCharacterInvincibilityImages(11) = My.Resources.Player15Hue120
            frmGameplay.aryCharacterInvincibilityImages(12) = My.Resources.Player15Hue130
            frmGameplay.aryCharacterInvincibilityImages(13) = My.Resources.Player15Hue140
            frmGameplay.aryCharacterInvincibilityImages(14) = My.Resources.Player15Hue150
            frmGameplay.aryCharacterInvincibilityImages(15) = My.Resources.Player15Hue160
            frmGameplay.aryCharacterInvincibilityImages(16) = My.Resources.Player15Hue170
            frmGameplay.aryCharacterInvincibilityImages(17) = My.Resources.Player15Hue180
            frmGameplay.aryCharacterInvincibilityImages(18) = My.Resources.Player15Hue190
            frmGameplay.aryCharacterInvincibilityImages(19) = My.Resources.Player15Hue200
            frmGameplay.aryCharacterInvincibilityImages(20) = My.Resources.Player15Hue210
            frmGameplay.aryCharacterInvincibilityImages(21) = My.Resources.Player15Hue220
            frmGameplay.aryCharacterInvincibilityImages(22) = My.Resources.Player15Hue230
            frmGameplay.aryCharacterInvincibilityImages(23) = My.Resources.Player15Hue240
            frmGameplay.aryCharacterInvincibilityImages(24) = My.Resources.Player15Hue250
            frmGameplay.aryCharacterInvincibilityImages(25) = My.Resources.Player15Hue260
            frmGameplay.aryCharacterInvincibilityImages(26) = My.Resources.Player15Hue270
            frmGameplay.aryCharacterInvincibilityImages(27) = My.Resources.Player15Hue280
            frmGameplay.aryCharacterInvincibilityImages(28) = My.Resources.Player15Hue290
            frmGameplay.aryCharacterInvincibilityImages(29) = My.Resources.Player15Hue300
            frmGameplay.aryCharacterInvincibilityImages(30) = My.Resources.Player15Hue310
            frmGameplay.aryCharacterInvincibilityImages(31) = My.Resources.Player15Hue320
            frmGameplay.aryCharacterInvincibilityImages(32) = My.Resources.Player15Hue330
            frmGameplay.aryCharacterInvincibilityImages(33) = My.Resources.Player15Hue340
            frmGameplay.aryCharacterInvincibilityImages(34) = My.Resources.Player15Hue350
            frmGameplay.aryCharacterInvincibilityImages(35) = My.Resources.Player15Hue360
        ElseIf frmCharactersList.varSelectedCharacter = 16 Then
            frmGameplay.aryCharacterInvincibilityImages(0) = My.Resources.Player16Hue10
            frmGameplay.aryCharacterInvincibilityImages(1) = My.Resources.Player16Hue20
            frmGameplay.aryCharacterInvincibilityImages(2) = My.Resources.Player16Hue30
            frmGameplay.aryCharacterInvincibilityImages(3) = My.Resources.Player16Hue40
            frmGameplay.aryCharacterInvincibilityImages(4) = My.Resources.Player16Hue50
            frmGameplay.aryCharacterInvincibilityImages(5) = My.Resources.Player16Hue60
            frmGameplay.aryCharacterInvincibilityImages(6) = My.Resources.Player16Hue70
            frmGameplay.aryCharacterInvincibilityImages(7) = My.Resources.Player16Hue80
            frmGameplay.aryCharacterInvincibilityImages(8) = My.Resources.Player16Hue90
            frmGameplay.aryCharacterInvincibilityImages(9) = My.Resources.Player16Hue100
            frmGameplay.aryCharacterInvincibilityImages(10) = My.Resources.Player16Hue110
            frmGameplay.aryCharacterInvincibilityImages(11) = My.Resources.Player16Hue120
            frmGameplay.aryCharacterInvincibilityImages(12) = My.Resources.Player16Hue130
            frmGameplay.aryCharacterInvincibilityImages(13) = My.Resources.Player16Hue140
            frmGameplay.aryCharacterInvincibilityImages(14) = My.Resources.Player16Hue150
            frmGameplay.aryCharacterInvincibilityImages(15) = My.Resources.Player16Hue160
            frmGameplay.aryCharacterInvincibilityImages(16) = My.Resources.Player16Hue170
            frmGameplay.aryCharacterInvincibilityImages(17) = My.Resources.Player16Hue180
            frmGameplay.aryCharacterInvincibilityImages(18) = My.Resources.Player16Hue190
            frmGameplay.aryCharacterInvincibilityImages(19) = My.Resources.Player16Hue200
            frmGameplay.aryCharacterInvincibilityImages(20) = My.Resources.Player16Hue210
            frmGameplay.aryCharacterInvincibilityImages(21) = My.Resources.Player16Hue220
            frmGameplay.aryCharacterInvincibilityImages(22) = My.Resources.Player16Hue230
            frmGameplay.aryCharacterInvincibilityImages(23) = My.Resources.Player16Hue240
            frmGameplay.aryCharacterInvincibilityImages(24) = My.Resources.Player16Hue250
            frmGameplay.aryCharacterInvincibilityImages(25) = My.Resources.Player16Hue260
            frmGameplay.aryCharacterInvincibilityImages(26) = My.Resources.Player16Hue270
            frmGameplay.aryCharacterInvincibilityImages(27) = My.Resources.Player16Hue280
            frmGameplay.aryCharacterInvincibilityImages(28) = My.Resources.Player16Hue290
            frmGameplay.aryCharacterInvincibilityImages(29) = My.Resources.Player16Hue300
            frmGameplay.aryCharacterInvincibilityImages(30) = My.Resources.Player16Hue310
            frmGameplay.aryCharacterInvincibilityImages(31) = My.Resources.Player16Hue320
            frmGameplay.aryCharacterInvincibilityImages(32) = My.Resources.Player16Hue330
            frmGameplay.aryCharacterInvincibilityImages(33) = My.Resources.Player16Hue340
            frmGameplay.aryCharacterInvincibilityImages(34) = My.Resources.Player16Hue350
            frmGameplay.aryCharacterInvincibilityImages(35) = My.Resources.Player16Hue360
        ElseIf frmCharactersList.varSelectedCharacter = 17 Then
            frmGameplay.aryCharacterInvincibilityImages(0) = My.Resources.Player17Hue10
            frmGameplay.aryCharacterInvincibilityImages(1) = My.Resources.Player17Hue20
            frmGameplay.aryCharacterInvincibilityImages(2) = My.Resources.Player17Hue30
            frmGameplay.aryCharacterInvincibilityImages(3) = My.Resources.Player17Hue40
            frmGameplay.aryCharacterInvincibilityImages(4) = My.Resources.Player17Hue50
            frmGameplay.aryCharacterInvincibilityImages(5) = My.Resources.Player17Hue60
            frmGameplay.aryCharacterInvincibilityImages(6) = My.Resources.Player17Hue70
            frmGameplay.aryCharacterInvincibilityImages(7) = My.Resources.Player17Hue80
            frmGameplay.aryCharacterInvincibilityImages(8) = My.Resources.Player17Hue90
            frmGameplay.aryCharacterInvincibilityImages(9) = My.Resources.Player17Hue100
            frmGameplay.aryCharacterInvincibilityImages(10) = My.Resources.Player17Hue110
            frmGameplay.aryCharacterInvincibilityImages(11) = My.Resources.Player17Hue120
            frmGameplay.aryCharacterInvincibilityImages(12) = My.Resources.Player17Hue130
            frmGameplay.aryCharacterInvincibilityImages(13) = My.Resources.Player17Hue140
            frmGameplay.aryCharacterInvincibilityImages(14) = My.Resources.Player17Hue150
            frmGameplay.aryCharacterInvincibilityImages(15) = My.Resources.Player17Hue160
            frmGameplay.aryCharacterInvincibilityImages(16) = My.Resources.Player17Hue170
            frmGameplay.aryCharacterInvincibilityImages(17) = My.Resources.Player17Hue180
            frmGameplay.aryCharacterInvincibilityImages(18) = My.Resources.Player17Hue190
            frmGameplay.aryCharacterInvincibilityImages(19) = My.Resources.Player17Hue200
            frmGameplay.aryCharacterInvincibilityImages(20) = My.Resources.Player17Hue210
            frmGameplay.aryCharacterInvincibilityImages(21) = My.Resources.Player17Hue220
            frmGameplay.aryCharacterInvincibilityImages(22) = My.Resources.Player17Hue230
            frmGameplay.aryCharacterInvincibilityImages(23) = My.Resources.Player17Hue240
            frmGameplay.aryCharacterInvincibilityImages(24) = My.Resources.Player17Hue250
            frmGameplay.aryCharacterInvincibilityImages(25) = My.Resources.Player17Hue260
            frmGameplay.aryCharacterInvincibilityImages(26) = My.Resources.Player17Hue270
            frmGameplay.aryCharacterInvincibilityImages(27) = My.Resources.Player17Hue280
            frmGameplay.aryCharacterInvincibilityImages(28) = My.Resources.Player17Hue290
            frmGameplay.aryCharacterInvincibilityImages(29) = My.Resources.Player17Hue300
            frmGameplay.aryCharacterInvincibilityImages(30) = My.Resources.Player17Hue310
            frmGameplay.aryCharacterInvincibilityImages(31) = My.Resources.Player17Hue320
            frmGameplay.aryCharacterInvincibilityImages(32) = My.Resources.Player17Hue330
            frmGameplay.aryCharacterInvincibilityImages(33) = My.Resources.Player17Hue340
            frmGameplay.aryCharacterInvincibilityImages(34) = My.Resources.Player17Hue350
            frmGameplay.aryCharacterInvincibilityImages(35) = My.Resources.Player17Hue360
        ElseIf frmCharactersList.varSelectedCharacter = 18 Then
            frmGameplay.aryCharacterInvincibilityImages(0) = My.Resources.Player18Hue10
            frmGameplay.aryCharacterInvincibilityImages(1) = My.Resources.Player18Hue20
            frmGameplay.aryCharacterInvincibilityImages(2) = My.Resources.Player18Hue30
            frmGameplay.aryCharacterInvincibilityImages(3) = My.Resources.Player18Hue40
            frmGameplay.aryCharacterInvincibilityImages(4) = My.Resources.Player18Hue50
            frmGameplay.aryCharacterInvincibilityImages(5) = My.Resources.Player18Hue60
            frmGameplay.aryCharacterInvincibilityImages(6) = My.Resources.Player18Hue70
            frmGameplay.aryCharacterInvincibilityImages(7) = My.Resources.Player18Hue80
            frmGameplay.aryCharacterInvincibilityImages(8) = My.Resources.Player18Hue90
            frmGameplay.aryCharacterInvincibilityImages(9) = My.Resources.Player18Hue100
            frmGameplay.aryCharacterInvincibilityImages(10) = My.Resources.Player18Hue110
            frmGameplay.aryCharacterInvincibilityImages(11) = My.Resources.Player18Hue120
            frmGameplay.aryCharacterInvincibilityImages(12) = My.Resources.Player18Hue130
            frmGameplay.aryCharacterInvincibilityImages(13) = My.Resources.Player18Hue140
            frmGameplay.aryCharacterInvincibilityImages(14) = My.Resources.Player18Hue150
            frmGameplay.aryCharacterInvincibilityImages(15) = My.Resources.Player18Hue160
            frmGameplay.aryCharacterInvincibilityImages(16) = My.Resources.Player18Hue170
            frmGameplay.aryCharacterInvincibilityImages(17) = My.Resources.Player18Hue180
            frmGameplay.aryCharacterInvincibilityImages(18) = My.Resources.Player18Hue190
            frmGameplay.aryCharacterInvincibilityImages(19) = My.Resources.Player18Hue200
            frmGameplay.aryCharacterInvincibilityImages(20) = My.Resources.Player18Hue210
            frmGameplay.aryCharacterInvincibilityImages(21) = My.Resources.Player18Hue220
            frmGameplay.aryCharacterInvincibilityImages(22) = My.Resources.Player18Hue230
            frmGameplay.aryCharacterInvincibilityImages(23) = My.Resources.Player18Hue240
            frmGameplay.aryCharacterInvincibilityImages(24) = My.Resources.Player18Hue250
            frmGameplay.aryCharacterInvincibilityImages(25) = My.Resources.Player18Hue260
            frmGameplay.aryCharacterInvincibilityImages(26) = My.Resources.Player18Hue270
            frmGameplay.aryCharacterInvincibilityImages(27) = My.Resources.Player18Hue280
            frmGameplay.aryCharacterInvincibilityImages(28) = My.Resources.Player18Hue290
            frmGameplay.aryCharacterInvincibilityImages(29) = My.Resources.Player18Hue300
            frmGameplay.aryCharacterInvincibilityImages(30) = My.Resources.Player18Hue310
            frmGameplay.aryCharacterInvincibilityImages(31) = My.Resources.Player18Hue320
            frmGameplay.aryCharacterInvincibilityImages(32) = My.Resources.Player18Hue330
            frmGameplay.aryCharacterInvincibilityImages(33) = My.Resources.Player18Hue340
            frmGameplay.aryCharacterInvincibilityImages(34) = My.Resources.Player18Hue350
            frmGameplay.aryCharacterInvincibilityImages(35) = My.Resources.Player18Hue360
        End If

    End Sub
End Class