'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SlotsMachine.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property addmoney_down() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("addmoney_down", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property addmoney_up() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("addmoney_up", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Background() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Background", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property betone_down() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("betone_down", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property betone_off() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("betone_off", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property betone_up() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("betone_up", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cashout_down() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cashout_down", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cashout_up() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cashout_up", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property payout() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("payout", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property pic1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pic1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pic2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pic2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pic3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pic3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pic4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pic4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pic5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pic5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property r0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("r0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property r1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("r1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property r10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("r10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property r11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("r11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property r12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("r12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property r13() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("r13", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property r14() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("r14", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property r15() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("r15", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property r16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("r16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property r17() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("r17", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property r18() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("r18", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property r19() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("r19", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property r2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("r2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property r20() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("r20", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property r21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("r21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property r22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("r22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property r23() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("r23", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property r3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("r3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property r4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("r4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property r5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("r5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property r6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("r6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property r7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("r7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property r8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("r8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property r9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("r9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property spin_down() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("spin_down", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property spin_off() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("spin_off", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property spin_real() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("spin_real", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property spin_up() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("spin_up", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
