'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("TankGame.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property picEnemyEast() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picEnemyEast", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property picEnemyNorth() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picEnemyNorth", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property picEnemyNorthEast() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picEnemyNorthEast", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property picEnemyNorthWest() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picEnemyNorthWest", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property picEnemySouth() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picEnemySouth", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property picEnemySouthEast() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picEnemySouthEast", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property picEnemySouthWest() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picEnemySouthWest", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property picEnemyWest() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picEnemyWest", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property picPlayerDown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picPlayerDown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property picPlayerEast() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picPlayerEast", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property picPlayerLeft() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picPlayerLeft", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property picPlayerLeft1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picPlayerLeft1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property picPlayerNorth() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picPlayerNorth", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property picPlayerNorthEast() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picPlayerNorthEast", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property picPlayerNorthWest() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picPlayerNorthWest", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property picPlayerRight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picPlayerRight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property picPlayerSouth() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picPlayerSouth", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property picPlayerSouthEast() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picPlayerSouthEast", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property picPlayerSouthWest() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picPlayerSouthWest", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property picPlayerTop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picPlayerTop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property picPlayerWest() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picPlayerWest", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
